### ISSUE TITLE
Problem on Lollipop 5 and 5.1

### ISSUE THREAD

**Issue by IronTony** [OpenGeeksMe/Android-File-Chooser#1]
Hello.
I have tested your webapp on Lollipop and the image isn't grabbed from the gallery. Instead on Marshmallow it works great.

**Comment by floryn90** [comment]
I fixed the code! Tell me if you have some problems with the code.

**Comment by IronTony** [comment]
Seems it doesn't get the image.
Here is the error:
at it.floryn90.webapp.MainActivity.createImageFile(MainActivity.java:142) 
                                                                      at it.floryn90.webapp.MainActivity.access$100(MainActivity.java:31) 
                                                                      at it.floryn90.webapp.MainActivity$PQChromeClient.onShowFileChooser(MainActivity.java:165)
